model_list:
  # Updated model list
  - model_name: qwen3-vl-plus
    litellm_params:
      model: openai/qwen3-vl-plus
      api_base: os.environ/IFLOW_API_BASE_CUSTOM
      api_key: os.environ/IFLOW_API_KEY_CUSTOM
  
  - model_name: claude-sonnet-4-5
    litellm_params:
      model: openai/claude-sonnet-4-5
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM
      
  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: openai/claude-opus-4-1-20250805
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM

  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: openai/claude-3-5-haiku-20241022
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM

  - model_name: Kimi-K2-Instruct-0905
    litellm_params:
      model: openai/Kimi-K2-Instruct-0905
      api_base: os.environ/IFLOW_API_BASE_CUSTOM
      api_key: os.environ/IFLOW_API_KEY_CUSTOM
      
  - model_name: glm-4.5
    litellm_params:
      model: openai/glm-4.5
      api_base: os.environ/IFLOW_API_BASE_CUSTOM
      api_key: os.environ/IFLOW_API_KEY_CUSTOM

  - model_name: qwen3-max
    litellm_params:
      model: openai/qwen3-max
      api_base: os.environ/IFLOW_API_BASE_CUSTOM
      api_key: os.environ/IFLOW_API_KEY_CUSTOM

  - model_name: deepseek-v3.1
    litellm_params:
      model: openai/deepseek-v3.1
      api_base: os.environ/IFLOW_API_BASE_CUSTOM
      api_key: os.environ/IFLOW_API_KEY_CUSTOM

  - model_name: gemini-2.5-pro
    litellm_params:
      model: openai/gemini-2.5-pro
      api_base: os.environ/GEMINI_API_BASE_CUSTOM
      api_key: os.environ/GEMINI_API_KEY_CUSTOM
