model_list:
  # Updated model list
  - model_name: DeepSeek-R1-0528
    litellm_params:
      model: openai/deepseek-ai/DeepSeek-R1-0528
      api_base: os.environ/FEATHERLESS_API_BASE_CUSTOM
      api_key: os.environ/FEATHERLESS_API_KEY_CUSTOM
      timeout: 60
      num_retries: 2
      rpm: 60
      tpm: 60000
  
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: openai/claude-sonnet-4-20250514
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM
      timeout: 60
      num_retries: 2
      rpm: 60
      tpm: 60000
      
  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: openai/claude-opus-4-1-20250805
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM
      timeout: 60
      num_retries: 2
      rpm: 60
      tpm: 60000

  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: openai/claude-3-5-haiku-20241022
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM
      timeout: 60
      num_retries: 2
      rpm: 60
      tpm: 60000

  - model_name: Kimi-K2-Instruct
    litellm_params:
      model: openai/moonshotai/Kimi-K2-Instruct
      api_base: os.environ/FEATHERLESS_API_BASE_CUSTOM
      api_key: os.environ/FEATHERLESS_API_KEY_CUSTOM
      timeout: 60
      num_retries: 2
      rpm: 60
      tpm: 60000
