model_list:
  # Updated model list
  - model_name: DeepSeek-R1-0528
    litellm_params:
      model: openai/deepseek-ai/DeepSeek-R1-0528
      api_base: os.environ/FEATHERLESS_API_BASE_CUSTOM
      api_key: os.environ/FEATHERLESS_API_KEY_CUSTOM
  
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: openai/claude-sonnet-4-20250514
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM
      
  - model_name: claude-opus-4-1-20250805
    litellm_params:
      model: openai/claude-opus-4-1-20250805
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM

  - model_name: claude-3-5-haiku-20241022
    litellm_params:
      model: openai/claude-3-5-haiku-20241022
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM

  - model_name: Kimi-K2-Instruct
    litellm_params:
      model: openai/moonshotai/Kimi-K2-Instruct
      api_base: os.environ/FEATHERLESS_API_BASE_CUSTOM
      api_key: os.environ/FEATHERLESS_API_KEY_CUSTOM
      
  - model_name: glm-4.5
    litellm_params:
      model: openai/glm-4.5
      api_base: os.environ/IFLOW_API_BASE_CUSTOM
      api_key: os.environ/IFLOW_API_KEY_CUSTOM

  - model_name: qwen3-max-preview
    litellm_params:
      model: openai/qwen3-max-preview
      api_base: os.environ/IFLOW_API_BASE_CUSTOM
      api_key: os.environ/IFLOW_API_KEY_CUSTOM

  - model_name: deepseek-v3.1
    litellm_params:
      model: openai/deepseek-v3.1
      api_base: os.environ/IFLOW_API_BASE_CUSTOM
      api_key: os.environ/IFLOW_API_KEY_CUSTOM
