model_list:
  # Existing example
  - model_name: DeepSeek-R1
    litellm_params:
      model: huggingface/deepseek-ai/DeepSeek-R1
      api_key: os.environ/HUGGINGFACE_API_KEY

  
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: openai/claude-sonnet-4-20250514
      api_base: os.environ/SONNET_API_BASE_CUSTOM
      api_key: os.environ/SONNET_API_KEY_CUSTOM
      timeout: 60
      num_retries: 2
      rpm: 60
      tpm: 60000
