model_list:
  # Updated model list
  - model_name: Qwen/Qwen3-VL-235B-A22B-Thinking
    litellm_params:
      model: openai/Qwen/Qwen3-VL-235B-A22B-Thinking
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: Qwen/Qwen2.5-VL-72B-Instruct
    litellm_params:
      model: openai/Qwen/Qwen2.5-VL-72B-Instruct
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: OpenGVLab/InternVL3-78B
    litellm_params:
      model: openai/OpenGVLab/InternVL3-78B
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: MiniMaxAI/MiniMax-M2
    litellm_params:
      model: openai/MiniMaxAI/MiniMax-M2
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: gemini-2.5-pro
    litellm_params:
      model: openai/gemini-2.5-pro
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: MiniMaxAI/MiniMax-M2
    litellm_params:
      model: openai/MiniMaxAI/MiniMax-M2
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: deepseek-ai/DeepSeek-V3.1
    litellm_params:
      model: openai/deepseek-ai/DeepSeek-V3.1
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: deepseek-ai/DeepSeek-R1-0528
    litellm_params:
      model: openai/deepseek-ai/DeepSeek-R1-0528
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: claude-sonnet-4-5
    litellm_params:
      model: openai/claude-sonnet-4-5
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: zai-org/GLM-4.6
    litellm_params:
      model: openai/zai-org/GLM-4.6
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: deepseek-ai/DeepSeek-V3.2-Exp
    litellm_params:
      model: openai/deepseek-ai/DeepSeek-V3.2-Exp
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: deepseek-ai/DeepSeek-OCR
    litellm_params:
      model: openai/deepseek-ai/DeepSeek-OCR
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  - model_name: moonshotai/Kimi-K2-Thinking
    litellm_params:
      model: openai/moonshotai/Kimi-K2-Thinking
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM

  # Updated model for audio transcription
  - model_name: FunAudioLLM/SenseVoiceSmall
    litellm_params:
      model: openai/FunAudioLLM/SenseVoiceSmall
      api_base: os.environ/IPIN_API_BASE_CUSTOM
      api_key: os.environ/IPIN_API_KEY_CUSTOM
    model_info:
      mode: audio_transcription
